spring:
  application:
    name: demo
  # 停机过程超时时长设置了20s，超过20s，直接停机
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 8080
  #  默认为IMMEDIATE，表示立即关机；GRACEFUL表示优雅关机
  shutdown: graceful

management:
  server:
    address: 127.0.0.1
    port: 50000
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /private-url
      exposure:
        include: health,shutdown
